# My Variables
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWU4ZDk1N2YyMDBhYTcyNjUyMWU0YzI1In0sImlhdCI6MTU4NjMzODcxNywiZXhwIjoxNTg2Njk4NzE3fQ.ChR446yYuA-D-w6cdYDDkH4WV65kYUNYHBoWg_7TIJ0
### Get request (auth)
GET http://localhost:5000/api/me
HEAD 
"Bearer Token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZjI2ZDkwNGJiOTMxYWZmMmNmNDVmYyIsImlhdCI6MTY0MzI4MDMwMSwiZXhwIjoxNjQ1ODcyMzAxfQ.OFDxE9VAyK0nbdLNGt05zMC7iyWcWhs5D_l3-RxK0Ck"

### Get contact
GET https://riisbitec.onrender.com/api/news


### Get contact
GET http://localhost:5000/api/mimic/videosurl

### Get languages
GET http://localhost:5000/api/tts/languages

### Get languages
GET http://localhost:5000/api/tts/voices/en-US

### Get languages
POST http://localhost:5000/api/tts/synthesis
Content-Type: application/json

{
   "language": "es-ES",
   "voice": "UTESM", 
   "text": "El cinturón de asteroides es una región del sistema solar comprendida aproximadamente entre las órbitas de Marte y Júpiter. Alberga multitud de objetos irregulares denominados asteroides o planetas menores. Esta región también se denomina cinturón principal con la finalidad de distinguirla de otras agrupaciones de planetas menores dentro del sistema solar, como el cinturón de Kuiper o el disco disperso. '"
}




### Post Request
POST https://100.100.100.52:5000/api/mimic/getAvatar
Content-Type: application/json

{
   "audio_url": "https://dialoga-machine-learning.s3.eu-west-1.amazonaws.com/mimic/audios/test123.wav",
   "avatar": "https://dialoga-machine-learning.s3.amazonaws.com/mimic/source/AnaBlanco_2.mp4"
}




### Get languages
POST https://100.100.100.52:5000/api/mimic/audio/
Content-Type: application/json

{
   "audio_url": "https://dialoga-machine-learning.s3.eu-west-1.amazonaws.com/mimic/audios/test123.wav"
}




### Post Request
GET https://riisbitec.onrender.com/api/machinelearning/stable_diffusion

### Register User
POST https://riisbitec.onrender.com/api/machinelearning/stable_diffusion
Content-Type: application/json

{
   "prompt": "Generate 3d model for the human face with mask"
}

### Register User
POST https://riisbitec.onrender.com/api/machinelearning//keywordextractor
Content-Type: application/json

{
   "text": "award winning high resolution photo of a giant tortoise/((ladybird)) hybrid, [trending on artstation]"
}


### chatgpt request
POST http://localhost:5000/api/chatgpt
Content-Type: application/json

{
   "text": "updated goal"
}


### loginuser
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
   "email": "whatever@gmail.com",
   "password": "1234567"
}
